name: Deploy AuraGarcia Webpage

on:
  push:
    branches:
      - main # Cambia 'main' por tu rama principal si es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Verificar secrets (DEBUG)
        run: |
          echo "Verificando secrets..."
          if [ -z "${{ secrets.FTP_SERVER }}" ]; then
            echo "❌ FTP_SERVER no está configurado"
          else
            echo "✅ FTP_SERVER está configurado"
          fi
          if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
            echo "❌ FTP_USERNAME no está configurado"
          else
            echo "✅ FTP_USERNAME está configurado"
          fi
          if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
            echo "❌ FTP_PASSWORD no está configurado"
          else
            echo "✅ FTP_PASSWORD está configurado"
          fi

      # Paso opcional: Si necesitas compilar, instalar dependencias, etc.
      # - name: Instalar dependencias
      #   run: npm install
      # - name: Compilar
      #   run: npm run build

      - name: Despliegue por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # Servidor FTP
          server: ${{ secrets.FTP_SERVER }}
          # Nombre de usuario FTP
          username: ${{ secrets.FTP_USERNAME }}
          # Contraseña FTP
          password: ${{ secrets.FTP_PASSWORD }}
          # Directorio local a subir (ej. 'dist' si se compila)
          local-dir: ./ # Sube todo el repositorio, ajusta si es necesario
          # Directorio remoto en el servidor FTP
          server-dir: /home/avragarc/public_html/ # Ajusta a la ruta de tu servidor
          # Opciones de protocolo, por defecto es 'ftp', usa 'ftps' para cifrado
          protocol: ftps
          # Otras opciones:
          # dry-run: true # Para probar sin subir
          # exclude: .git .github