name: Deploy AuraGarcia Webpage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
      continue-on-error: true
      
    - name: Validate HTML
      run: |
        echo "Validating HTML structure..."
        if command -v html5validator &> /dev/null; then
          html5validator --root . --ignore "node_modules/*"
        else
          echo "HTML5 validator not available, skipping validation"
        fi
      continue-on-error: true
      
    - name: Check for broken links
      run: |
        echo "Checking for broken links..."
        if command -v linkchecker &> /dev/null; then
          linkchecker --check-extern index.html
        else
          echo "Link checker not available, skipping link validation"
        fi
      continue-on-error: true
      
    - name: Optimize images
      run: |
        echo "Checking image optimization..."
        find resources/ -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" | head -5 | while read img; do
          echo "Found image: $img"
          if command -v identify &> /dev/null; then
            identify "$img" | head -1
          fi
        done
      continue-on-error: true
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          .github/
          .gitignore
          README.md
          PROJECT_STRUCTURE.md
          docs/
          resources/manual_identidad/
          
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful! Your webpage is live at:"
          echo "https://auragarciamx.github.io/webpage/"
        else
          echo "❌ Deployment failed. Please check the logs."
        fi
